# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: vicky
  demands:
   - agent.Name -equals vickyWindowsSelfHosted 

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: katalonTask@1
  inputs:
    version: '8.2.5'
    executeArgs: ' -retry=0 -testSuitePath="Test Suites/start winappdriver by script" -browserType="Windows" -executionProfile="default" -apiKey="2199b58d-de67-448a-9135-4b29ee9c53bf"'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
